make:
	g++ -std=c++11 -Wall Menu.cpp Pokemon.cpp Player.cpp Person.cpp Computer.cpp Battle.cpp BattleMenu.cpp main.cpp
	./a.out

v2:
	g++ -std=c++11 -Wall Menu.cpp Pokemon.cpp Player.cpp Person.cpp Computer.cpp Battle.cpp BattleMenu.cpp main2.cpp
	./a.out
