make game:
	g++ -std=c++11 -Wall Menu.cpp Pokemon.cpp Player.cpp Person.cpp Computer.cpp Battle.cpp BattleMenu.cpp main.cpp
	./a.out

battle:
	g++ -std=c++11 -Wall Pokemon.cpp Player.cpp Person.cpp Computer.cpp Battle.cpp BattleDriver.cpp
	./a.out
