make:
	g++ -std=c++11 -Wall Pokemon.cpp Player.cpp Person.cpp Menu.cpp main.cpp
	./a.out

player:
	g++ -std=c++11 -Wall Pokemon.cpp Player.cpp playerDriver.cpp
	./a.out

menu:
	g++ -std=c++11 -Wall Menu.cpp menuDriver.cpp
	./a.out
	
pokemonMenu:
	g++ -std=c++11 -Wall Pokemon.cpp Player.cpp PokemonMenu.cpp pokemonMenuDriver.cpp
	./a.out
