make:
	g++ -std=c++11 -Wall Pokemon.cpp Trainer.cpp Player.cpp Person.cpp Menu.cpp Computer.cpp BattleMenu.cpp Battle.cpp main.cpp
	./a.out

player:
	g++ -std=c++11 -Wall Pokemon.cpp Player.cpp playerDriver.cpp
	./a.out

menu:
	g++ -std=c++11 -Wall Menu.cpp menuDriver.cpp
	./a.out
	
pokemonMenu:
	g++ -std=c++11 -Wall Pokemon.cpp Player.cpp PokemonMenu.cpp pokemonMenuDriver.cpp
	./a.out

computer:
	g++ -std=c++11 -Wall Pokemon.cpp Player.cpp Computer.cpp computerDriver.cpp
	./a.out

battle:
	g++ -std=c++11 -Wall Pokemon.cpp Trainer.cpp Player.cpp Computer.cpp Battle.cpp battleDriver.cpp
	./a.out
